config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get "/security_answers/verify", to: "security_answers#verify"
  # get "/security_answers/find_user", to: "security_answers#find_user"

  get "/users/find_user", to: "users#find_user"
  get "/security_answers/:id/verify", to: "security_answers#verify"

  resources :users

  resources :recipes
  resources :ingredients
  resources :login
  resources :security_questions
  # get "/security_answers/:id"
  resources :security_answers
  delete "/logout", to: "login#destroy"


 #this --> resources :login, only: [:new, :create] is the same as   get '/login' => 'login#new' and post '/login' => 'login#create'

  # root 'welcome#home'

  # get '/login' => 'login#new'
  # post '/login' => 'login#create'
  # root 'application#hello'
  # post '/logout' => 'sessions#destroy'


  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'

  # get '/' => ''
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  has_one_attached :food_photo


  validates :name, presence: true, uniqueness: true

end

app/models/security_answer.rb
class SecurityAnswer < ApplicationRecord
  belongs_to :security_question
  belongs_to :user



  # 
  # def self.verify_answers
  #   if self.answer_1 == :answer_1 && self.answer_2 == :answer_2 && self.answer_3 == :answer_3
  #
  #
  # end
end

app/models/security_question.rb
class SecurityQuestion < ApplicationRecord
  has_many :security_answers
  has_many :users, through: :security_answers
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes
  has_many :security_answers
  has_many :security_questions, through: :security_answers

  has_secure_password

  validates :user_name, uniqueness: true, presence: true

  def self.search(user_name)
    if :user_name
        where('USERNAME LIKE ?', "%#{user_name}%")
    else
        all
    end
end


  # def password=(pass)
  #   self.password_digest = BCrypt::Password.create(pass)
  # end
  #
  # def authenticate(plain_text_password)
  #   BCrypt::Password.new(self.password_digest) == plain_text_password
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :setup
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  #
  # def current_user
  #   @user = (User.find_by(id: session[:user_id]) || User.new)
  # end
  #
  # def logged_in?
  #   current_user.id != nil
  # end
  #
  # def require_logged_in
  #   return redirect_to(controller: 'sessions', action: 'new') unless logged_in?
  # end
  def setup
    @user_id = session[:user_id]
    @logged_in = !!@user_id
    if @logged_in
      @current_user = User.find(@user_id)
  end
end

def logout
  session[:user_id] = nil
end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  # def new
  # end
  #routes pattern: route controller method
  def create
    # return redirect_to(controller: 'sessions',
    #                    action: 'new') if !params[:user_name] || params[:password].empty?
    # session[:user_name] = params[:user_name]
    # session[:password] = params[:password]
    # redirect_to controller: 'application', action: 'hello'
    @user = User.find_by(user_name: params[:user_name])
    if @user && @user.authenticate(params[:password])
      # flash[:messages] =  "Logging in #{@user.name}."
      session[:user_id] = @user.id
      redirect_to "/users/#{@user.id}"
    else
      flash[:messages] = "Incorrect username or password"
      redirect_to new_login_path
  end


end

  def destroy
    logout
    redirect_to new_login_path
  end

  # def new
  #   @user = User.find(params[:id])
  # end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
    # @ingredients = Ingredient.all
    @users = User.all
    # @current_user = User

  end

  def new
    # @ingredients = Ingredient.all
    @users = User.all
    # @user = User.find(params[:id])
    # @ingredients = Ingredient.all
    @recipe = Recipe.new
    # @ingredients = Ingredient.all
    # @users.User.all
    @current_user = User.find(session[:user_id])
    end

  def create
    @recipe = Recipe.create(recipe_params)

    if @recipe.valid?
    redirect_to @recipe
  else
    flash[:errors] = @recipe.errors.full_messages
    redirect_to new_recipe_path
  end
end

    # redirect_to @recipe


  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)
    redirect_to @recipe
  end

  def edit
    @recipe = Recipe.find(params[:id])
    # @recipe.food_photo.attach(params[:food_photo])
  end

  def show
    @recipe = Recipe.find(params[:id])

    # @current_user = @recipe.current_user
    # @current_user = @recipe.current_user
    # @ingredient = @recipe.ingredients
    # @user = @recipe.user
    # @user = Recipe.user

  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to recipe
  end

  private

  def recipe_params
    # params.require(:recipe).permit(:name, :ingredients, @current_user.id)
    params.require(:recipe).permit(:name, :ingredients, :user_id, :food_photo)
  end
end

app/controllers/security_answers_controller.rb
class SecurityAnswersController < ApplicationController
  def index
    @security_answers = SecurityAnswer.all
    @users = User.all

  end

  def edit
    @security_answer = SecurityAnswer.find(params[:id])

  end

  def update
    security_answer = SecurityAnswer.find(params[:id])
    security_answer.update
    redirect_to security_answer
  end

  def new
    @security_answer = SecurityAnswer.new
    @security_questions = SecurityQuestion.all
    @users = User.all
    @current_user = User.find(session[:user_id])


  end

  def create
    @security_answer = SecurityAnswer.create(security_answers_params)
    redirect_to @current_user

  end

  def verify
    @security_answer = SecurityAnswer.new
    @security_questions = SecurityQuestion.all
    @users = User.all
    @current_user = User.find(session[:user_id])
  end




  def security_answers_params
    params.require(:security_answer).permit(:answer_1, :answer_2, :answer_3, :security_question_id, :user_id)

  end
end

app/controllers/security_questions_controller.rb
class SecurityQuestionsController < ApplicationController
  def index
    @security_questions = SecurityQuestion.all
  end

  def new
    @security_question = SecurityQuestion.new
  end

  def show
    @security_question = SecurityQuestion.find(params[:id])
  end

  # def edit
  # end
  #
  # def update
  # end

  private
  def security_question_params
    params.require(:security_question).permit()
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @recipes = Recipe.all
  end

  def new
    # @current_user = User.new
    @user = User.new
    @recipes = Recipe.all
    @security_questions = SecurityQuestion.all
    # @security_answer = SecurityAnswer.new
  end

  def create
    @security_answer = SecurityAnswer.new
    @user = User.create(user_params)
    # return redirect_to controller: 'users', action: 'new' unless @user.save
    # session[:user_id] = @user.id
    # redirect_to controller: 'welcome', action: 'home'
    # redirect_to user
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to "/security_answers/new"
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path

  end
end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    @security_answer = SecurityAnswer.all
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user

  end

  def myrecipe
    @user = User.find(params[:id])
  end


  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to "/login/new"
   #  session.delete :user_id
   # redirect_to '/'
  end

  def find_user
    # @user = User.find(params[:user_name])
    # @user = User.all
    @users = User.search(params[:search])
    redirect_to "/security_answers/#{@user.id}/verify"
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/security_answers_helper.rb
module SecurityAnswersHelper
end

app/helpers/security_questions_helper.rb
module SecurityQuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllergenRailsLab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  
  </head>

  <body>
    <!-- <img src = "../images/IMG_1097.jpg" alt =""> -->
    <header>
      <% if @logged_in %>
      <h3>
        Logged in as: <%=@current_user.name %>
      </h3>
         <%= button_to "Log out #{@current_user.name}", "/logout", method: :delete %>
           <% else %>
             <% end %>
    <%= yield %>
    </header>


  </body>
</html>

app/views/login/new.html.erb
<h1>Welcome to Share my Recipes</h1>

<% if flash[:errors] %>
<ul>
  <% flash[:errors].each do |error_msg| %>
  <li>
    <%= error_msg %>
    </li>
    <%end%>
  </ul>
  <%end%>

<h4>Use the login form below to access your credentials </h4>
<br>

<%= form_tag "/login" do %>
<%= label_tag :user_name %>
<%= text_field_tag :user_name %>
<%= label_tag :password %>
<%= password_field_tag :password %>
<%= submit_tag "Login" %>
<% end %>

<p>If you do not have an account with us <%= link_to "Click Here", "/users/new" %> to create one</p>
<p> If you forgot your password <%= link_to "Click Here", "/users/find_user" %> to reset </p>

app/views/recipes/index.html.erb
<h2> <%= @current_user.name %>'s Recipe's</h2>

  <% @current_user.recipes.each do |recipe| %>
  <p><%=link_to recipe.name, recipe %></p>
<% end %>

<br>

<%= link_to "Back to Home Page", user_path(@current_user) %>

app/views/recipes/new.html.erb
<h1>Create A New Recipe</h1>
<% if flash[:errors] %>
<ul>
  <% flash[:errors].each do |error_msg| %>
  <li>
    <%= error_msg %>
    </li>
    <%end%>
  </ul>
  <%end%>

<%= form_for @recipe do |form| %>
<%= form.label :name %>
<%= form.text_field :name %>
<%= form.label :ingredients %>
<%= form.text_field :ingredients %>
<%= form.collection_select :user_id, @users, :id, :name%>
<%# collection_select "ingredient_id", @ingredients, :id, :name%>
<%= form.label "Upload Photo" %>
<%= form.file_field :food_photo %>
<%= form.submit %>
<% end %>
<br>

<%= link_to "Back to Home Page", user_path(@current_user) %>

app/views/recipes/show.html.erb
<h2><%=@recipe.name%></h2>

<% if @recipe.food_photo.attached? %>
<image src = "<%=(url_for(@recipe.food_photo))%>">
<% end %>

<h3>Ingredients</h3>

<p> <%= @recipe.ingredients %> </p>

<%= button_to "Delete #{@recipe.name}", "/recipes/#{@recipe.id}", method: :delete %>

app/views/security_answers/index.html.erb
<h2>Answers to the security Questions</h2>


<ul>
<% @current_user.security_answers.each do |sec_ans|%>
<p>
1. <%=sec_ans.answer_1%>
<br>
2. <%=sec_ans.answer_2%>
<br>
3. <%=sec_ans.answer_3%>
  </p>
</ul>
<% end %>

<%= link_to "Back to Home Page", user_path(@current_user) %>

app/views/security_answers/new.html.erb
<h2>Please answer these questions that will assist you in reseting your password in the future</h2>

<%= form_for @security_answer do |form| %>
<%= form.label :user_id %>
<%= form.collection_select :user_id, @users, :id, :name %>
<%= form.label :security_question_id %>
<%= form.collection_select :security_question_id, @security_questions, :id, :question_1 %>
<%= form.text_field :answer_1 %>
<%= form.collection_select :security_question_id, @security_questions, :id, :question_2 %>
<%= form.text_field :answer_2 %>
<%= form.collection_select :security_question_id, @security_questions, :id, :question_3 %>
<%= form.text_field :answer_3 %>
<%= form.submit "Submit Answers" %>

<% end %>

app/views/security_answers/verify.html.erb
<!-- <h2>To reset your password you must verify your answers to the questions below</h2> -->

app/views/users/edit.html.erb
<h2>Edit Account Information for <%=@user.name%></h2>

<%= form_for @user do |form| %>
<%= form.label :user_name %>
<%= form.text_field :user_name %>
<%= form.label :password %>
<%= form.text_field :password %>
<%= form.submit %>
<% end %>

<br>

<%= link_to "Back to Home Page" , user_path %>

app/views/users/find_user.html.erb
<h2>Please Enter the Username associated with your account</h2>

<%= form_tag users_path, :method => 'get', :id => 'users_search' do %>
    <p> <%= label_tag(:user_name, "Search for:") %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :user_name => nil %>
    </p>
<% end %>

app/views/users/myrecipe.html.erb
<h3>Recipes</h3>
<ul>
  <% @user.recipes.each do |my_recipe|%>
  <p>Name: <%=link_to my_recipe.name, my_recipe%> </p>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Create Account</h1>


<%= form_for @user, controller: 'users', action: 'create' do |form| %>
<%= form.label :name %>
<%= form.text_field :name %>
<%= form.label :user_name %>
<%= form.text_field :user_name %>
<%= form.label :password%>
<%= form.password_field :password %>
<%= form.submit %>
<% end %>

app/views/users/show.html.erb
<h3>Account Information</h3>
<p>Username: <%=@user.user_name %></p>
<p>Password: ******** </p>

<p><%= link_to "Change Username or Password" , "/users/#{@user.id}/edit" %></p>

<p><%= link_to "Create A New Recipe", "/recipes/new" %></p>

<p><%= link_to "View My Recipes", "/recipes/" %></p>

<p><%= link_to "View/Edit Security Answers", "/security_answers/" %></p>